/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FutbolAmericanoRouteImport } from './routes/futbol-americano'
import { Route as FutbolDeCampoRouteImport } from './routes/futbol-de-campo'
import { Route as LosDosDeportesRouteImport } from './routes/los-dos-deportes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FutbolAmericanoRoute = FutbolAmericanoRouteImport.update({
  id: '/futbol-americano',
  path: '/futbol-americano',
  getParentRoute: () => rootRouteImport,
} as any)
const FutbolDeCampoRoute = FutbolDeCampoRouteImport.update({
  id: '/futbol-de-campo',
  path: '/futbol-de-campo',
  getParentRoute: () => rootRouteImport,
} as any)
const LosDosDeportesRoute = LosDosDeportesRouteImport.update({
  id: '/los-dos-deportes',
  path: '/los-dos-deportes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/futbol-americano': typeof FutbolAmericanoRoute
  '/futbol-de-campo': typeof FutbolDeCampoRoute
  '/los-dos-deportes': typeof LosDosDeportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/futbol-americano': typeof FutbolAmericanoRoute
  '/futbol-de-campo': typeof FutbolDeCampoRoute
  '/los-dos-deportes': typeof LosDosDeportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/futbol-americano': typeof FutbolAmericanoRoute
  '/futbol-de-campo': typeof FutbolDeCampoRoute
  '/los-dos-deportes': typeof LosDosDeportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/futbol-americano' | '/futbol-de-campo' | '/los-dos-deportes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/futbol-americano' | '/futbol-de-campo' | '/los-dos-deportes'
  id:
    | '__root__'
    | '/'
    | '/futbol-americano'
    | '/futbol-de-campo'
    | '/los-dos-deportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FutbolAmericanoRoute: typeof FutbolAmericanoRoute
  FutbolDeCampoRoute: typeof FutbolDeCampoRoute
  LosDosDeportesRoute: typeof LosDosDeportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futbol-americano': {
      id: '/futbol-americano'
      path: '/futbol-americano'
      fullPath: '/futbol-americano'
      preLoaderRoute: typeof FutbolAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futbol-de-campo': {
      id: '/futbol-de-campo'
      path: '/futbol-de-campo'
      fullPath: '/futbol-de-campo'
      preLoaderRoute: typeof FutbolDeCampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/los-dos-deportes': {
      id: '/los-dos-deportes'
      path: '/los-dos-deportes'
      fullPath: '/los-dos-deportes'
      preLoaderRoute: typeof LosDosDeportesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FutbolAmericanoRoute: FutbolAmericanoRoute,
  FutbolDeCampoRoute: FutbolDeCampoRoute,
  LosDosDeportesRoute: LosDosDeportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
